development:
  adapter: mysql2
  database: wedding_website_development
  username: ewryan
  password: moomoofarm

test:
  adapter: mysql2
  database: wedding_website_test
  username: ewryan
  password: moomoofarm

production:
  adapter: postgresql
  database: wedding_website_production
  username: ewryan
  password: moomoofarm