development:
  host: localhost
  adapter: postgresql
  database: wedding_website_development
  username: 
  password: 

test:
  adapter: postgresql
  database: wedding_website_test
  username: ewryan
  password: moomoofarm

production:
  adapter: postgresql
  database: wedding_website_production
  username: ewryan
  password: moomoofarm